#include "pcg_converter.h"

std::vector<PCG_Converter::GMInfo> PCG_Converter::m_gmInfo = {
	{ "GM"  , 1      , "s", "Acoustic Piano"},
	{ "g(1)", 1      , "s", "Acoustic Piano w"},
	{ "g(2)", 1      , "s", "Acoustic Piano d"},
	{ "GM"  , 2      , "s", "Bright Piano"},
	{ "g(1)", 2      , "s", "Bright Piano w"},
	{ "GM"  , 3      , "s", "El.Grand Piano"},
	{ "g(1)", 3      , "s", "El.Grand Piano w"},
	{ "GM"  , 4      , "d", "Honkey-Tonk"},
	{ "g(1)", 4      , "d", "Honkey-Tonk w"},
	{ "GM"  , 5      , "s", "Electric Piano 1"},
	{ "g(1)", 5      , "d", "Detuned E.Piano1"},
	{ "g(2)", 5      , "d", "ElectricPiano1 v"},
	{ "g(3)", 5      , "s", "60's E.Piano"},
	{ "GM"  , 6      , "s", "Electric Piano 2"},
	{ "g(1)", 6      , "d", "Detuned E.Piano2"},
	{ "g(2)", 6      , "d", "ElectricPiano2 v"},
	{ "g(3)", 6      , "d", "E.Piano Legend"},
	{ "g(4)", 6      , "d", "E.Piano Phase"},
	{ "GM"  , 7      , "s", "Harpsichord"},
	{ "g(1)", 7      , "d", "Harpsi. oct-mix"},
	{ "g(2)", 7      , "s", "Harpsichord w"},
	{ "g(3)", 7      , "d", "Harpsi. key-off"},
	{ "GM"  , 8      , "s", "Clavi."},
	{ "g(1)", 8      , "s", "Pulse Clavi."},
	{ "GM"  , 9      , "s", "Celesta"},
	{ "GM"  , 10     , "d", "Glockenspiel"},
	{ "GM"  , 11     , "s", "Music Box"},
	{ "GM"  , 12     , "s", "Vibraphone"},
	{ "g(1)", 12     , "s", "Vibraphone w"},
	{ "GM"  , 13     , "s", "Marimba"},
	{ "g(1)", 13     , "s", "Marimba w"},
	{ "GM"  , 14     , "s", "Xylophone"},
	{ "GM"  , 15     , "s", "Tubular Bells"},
	{ "g(1)", 15     , "d", "Church Bell"},
	{ "g(2)", 15     , "d", "Carillon"},
	{ "GM"  , 16     , "s", "Santur"},
	{ "GM"  , 17     , "s", "Drawbar Organ 1"},
	{ "g(1)", 17     , "d", "Det.DrawbarOrgan"},
	{ "g(2)", 17     , "s", "Italian60'sOrgan"},
	{ "g(3)", 17     , "d", "Drawbar Organ 2"},
	{ "GM"  , 18     , "s", "PercussiveOrgan1"},
	{ "g(1)", 18     , "d", "Det.Perc-Organ"},
	{ "g(2)", 18     , "d", "PercussiveOrgan2"},
	{ "GM"  , 19     , "s", "Rock Organ"},
	{ "GM"  , 20     , "s", "Church Organ"},
	{ "g(1)", 20     , "d", "Church Org Oct."},
	{ "g(2)", 20     , "d", "Det.Church Org"},
	{ "GM"  , 21     , "d", "Reed Organ"},
	{ "g(1)", 21     , "d", "Puff Organ"},
	{ "GM"  , 22     , "d", "Accordion 1"},
	{ "g(1)", 22     , "s", "Accordion 2"},
	{ "GM"  , 23     , "s", "Harmonica"},
	{ "GM"  , 24     , "d", "Bandoneon"},
	{ "GM"  , 25     , "s", "Nylon Guitar 1"},
	{ "g(1)", 25     , "s", "Ukulele"},
	{ "g(2)", 25     , "d", "NylonGtr.key-off"},
	{ "g(3)", 25     , "s", "Nylon Guitar 2"},
	{ "GM"  , 26     , "s", "Steel Guitar"},
	{ "g(1)", 26     , "d", "12-StringsGuitar"},
	{ "g(2)", 26     , "s", "Mandolin"},
	{ "g(3)", 26     , "d", "Steel Gtr. Body"},
	{ "GM"  , 27     , "s", "Jazz Guitar"},
	{ "g(1)", 27     , "s", "Pedal Steel Gtr."},
	{ "GM"  , 28     , "s", "Clean Guitar"},
	{ "g(1)", 28     , "d", "Detuned Clean Gt"},
	{ "g(2)", 28     , "d", "Mid Tone Guitar"},
	{ "GM"  , 29     , "s", "Muted Guitar"},
	{ "g(1)", 29     , "s", "Funky Guitar"},
	{ "g(2)", 29     , "d", "Muted Guitar v"},
	{ "g(3)", 29     , "d", "Jazz Man"},
	{ "GM"  , 30     , "s", "Overdrive Guitar"},
	{ "g(1)", 30     , "s", "Guitar Pinch"},
	{ "GM"  , 31     , "s", "DistortionGuitar"},
	{ "g(1)", 31     , "d", "Feedback Guitar"},
	{ "g(2)", 31     , "s", "Dist. Rhythm Gtr"},
	{ "GM"  , 32     , "s", "Guitar Harmonics"},
	{ "g(1)", 32     , "s", "Guitar Feedback"},
	{ "GM"  , 33     , "d", "Acoustic Bass"},
	{ "GM"  , 34     , "d", "Fingered Bass"},
	{ "g(1)", 34     , "d", "Finger Slap Bass"},
	{ "GM"  , 35     , "d", "Picked Bass"},
	{ "GM"  , 36     , "d", "Fretless Bass"},
	{ "GM"  , 37     , "d", "Slap Bass 1"},
	{ "GM"  , 38     , "d", "Slap Bass 2"},
	{ "GM"  , 39     , "d", "Synth Bass 1"},
	{ "g(1)", 39     , "d", "Warm Synth Bass"},
	{ "g(2)", 39     , "d", "Synth Bass 3"},
	{ "g(3)", 39     , "d", "Clavi Bass"},
	{ "g(4)", 39     , "d", "Hammer"},
	{ "GM"  , 40     , "s", "Synth Bass 2"},
	{ "g(1)", 40     , "d", "Synth Bass 4"},
	{ "g(2)", 40     , "d", "Rubber Bass"},
	{ "g(3)", 40     , "s", "Attack Pulse"},
	{ "GM"  , 41     , "s", "Violin"},
	{ "g(1)", 41     , "s", "Slow Violin"},
	{ "GM"  , 42     , "s", "Viola"},
	{ "GM"  , 43     , "s", "Cello"},
	{ "GM"  , 44     , "s", "Contrabass"},
	{ "GM"  , 45     , "s", "Tremolo Strings"},
	{ "GM"  , 46     , "s", "Pizzicato Str."},
	{ "GM"  , 47     , "s", "Orchestral Harp"},
	{ "g(1)", 47     , "d", "Yang Chin"},
	{ "GM"  , 48     , "d", "Timpani"},
	{ "GM"  , 49     , "s", "Strings"},
	{ "g(1)", 49     , "d", "Strings & Brass"},
	{ "g(2)", 49     , "d", "60's Strings"},
	{ "GM"  , 50     , "s", "Slow Strings"},
	{ "GM"  , 51     , "d", "Synth Strings 1"},
	{ "g(1)", 51     , "d", "Synth Strings 3"},
	{ "GM"  , 52     , "s", "Synth Strings 2"},
	{ "GM"  , 53     , "s", "Choir Aahs 1"},
	{ "g(1)", 53     , "s", "Choir Aahs 2"},
	{ "GM"  , 54     , "s", "Voice Oohs"},
	{ "g(1)", 54     , "d", "Humming"},
	{ "GM"  , 55     , "s", "Synth Vox"},
	{ "g(1)", 55     , "s", "Analog Voice"},
	{ "GM"  , 56     , "s", "Orchestra Hit"},
	{ "g(1)", 56     , "d", "Bass Hit Plus"},
	{ "g(2)", 56     , "d", "6th Hit"},
	{ "g(3)", 56     , "d", "Euro Hit"},
	{ "GM"  , 57     , "s", "Trumpet"},
	{ "g(1)", 57     , "s", "Soft Trumpet"},
	{ "GM"  , 58     , "s", "Trombone 1"},
	{ "g(1)", 58     , "d", "Trombone 2"},
	{ "g(2)", 58     , "s", "Bright Trombone"},
	{ "GM"  , 59     , "s", "Tuba"},
	{ "GM"  , 60     , "s", "Muted Trumpet 1"},
	{ "g(1)", 60     , "s", "Muted Trumpet 2"},
	{ "GM"  , 61     , "s", "French Horn"},
	{ "g(1)", 61     , "d", "Warm French Horn"},
	{ "GM"  , 62     , "s", "Brass Section 1"},
	{ "g(1)", 62     , "d", "Brass Section 2"},
	{ "GM"  , 63     , "d", "Synth Brass 1"},
	{ "g(1)", 63     , "d", "Synth Brass 3"},
	{ "g(2)", 63     , "d", "Analog Brass 1"},
	{ "g(3)", 63     , "d", "Jump Brass"},
	{ "GM"  , 64     , "s", "Synth Brass 2"},
	{ "g(1)", 64     , "s", "Synth Brass 4"},
	{ "g(2)", 64     , "d", "Analog Brass 2"},
	{ "GM"  , 65     , "s", "Soprano Sax"},
	{ "GM"  , 66     , "s", "Alto Sax"},
	{ "GM"  , 67     , "s", "Tenor Sax"},
	{ "GM"  , 68     , "s", "Baritone Sax"},
	{ "GM"  , 69     , "s", "Oboe"},
	{ "GM"  , 70     , "s", "English Horn"},
	{ "GM"  , 71     , "s", "Bassoon"},
	{ "GM"  , 72     , "s", "Clarinet"},
	{ "GM"  , 73     , "s", "Piccolo"},
	{ "GM"  , 74     , "s", "Flute"},
	{ "GM"  , 75     , "s", "Recorder"},
	{ "GM"  , 76     , "s", "Pan Flute"},
	{ "GM"  , 77     , "d", "Blown Bottle"},
	{ "GM"  , 78     , "d", "Shakuhachi"},
	{ "GM"  , 79     , "s", "Whistle"},
	{ "GM"  , 80     , "s", "Ocarina"},
	{ "GM"  , 81     , "d", "Detuned Square"},
	{ "g(1)", 81     , "s", "Simple Square"},
	{ "g(2)", 81     , "s", "Simple Sine"},
	{ "GM"  , 82     , "d", "Detuned Sawtooth"},
	{ "g(1)", 82     , "s", "Simple Sawtooth"},
	{ "g(2)", 82     , "d", "Sawtooth + Pulse"},
	{ "g(3)", 82     , "d", "Double Sawtooth"},
	{ "g(4)", 82     , "d", "Sequenced Analog"},
	{ "GM"  , 83     , "d", "Synth Calliope"},
	{ "GM"  , 84     , "d", "Chiff Lead"},
	{ "GM"  , 85     , "d", "Charang"},
	{ "g(1)", 85     , "d", "Wire Lead"},
	{ "GM"  , 86     , "d", "Air Voice"},
	{ "GM"  , 87     , "d", "5th Sawtooth"},
	{ "GM"  , 88     , "s", "Bass & Lead"},
	{ "g(1)", 88     , "d", "Soft Wurl"},
	{ "GM"  , 89     , "d", "Fantasia"},
	{ "GM"  , 90     , "s", "Warm Pad"},
	{ "g(1)", 90     , "d", "Sine Pad"},
	{ "GM"  , 91     , "d", "Polyphonic Synth"},
	{ "GM"  , 92     , "d", "Space Voice"},
	{ "g(1)", 92     , "d", "Itopia"},
	{ "GM"  , 93     , "d", "Bowed Glass"},
	{ "GM"  , 94     , "d", "Metallic Pad"},
	{ "GM"  , 95     , "d", "Halo Pad"},
	{ "GM"  , 96     , "s", "Sweep Pad"},
	{ "GM"  , 97     , "d", "Ice Rain"},
	{ "GM"  , 98     , "d", "Sound Track"},
	{ "GM"  , 99     , "d", "Crystal"},
	{ "g(1)", 99     , "s", "Synth Mallet"},
	{ "GM"  , 100     , "d", "Atmosphere"},
	{ "GM"  , 101     , "d", "Brightness"},
	{ "GM"  , 102     , "d", "Goblins"},
	{ "GM"  , 103     , "s", "Echo Drops"},
	{ "g(1)", 103     , "d", "Echo Bell"},
	{ "g(2)", 103     , "d", "Echo Pan"},
	{ "GM"  , 104     , "d", "Star Theme"},
	{ "GM"  , 105     , "s", "Sitar 1"},
	{ "g(1)", 105     , "d", "Sitar 2"},
	{ "GM"  , 106     , "s", "Banjo"},
	{ "GM"  , 107     , "s", "Shamisen"},
	{ "GM"  , 108     , "s", "Koto"},
	{ "g(1)", 108     , "d", "Taisho Koto"},
	{ "GM"  , 109     , "s", "Kalimba"},
	{ "GM"  , 110     , "d", "Bagpipe"},
	{ "GM"  , 111     , "s", "Fiddle"},
	{ "GM"  , 112     , "s", "Shanai"},
	{ "GM"  , 113     , "d", "Tinkle Bell"},
	{ "GM"  , 114     , "s", "Agogo"},
	{ "GM"  , 115     , "d", "Steel Drums"},
	{ "GM"  , 116     , "s", "Woodblock"},
	{ "g(1)", 116     , "s", "Castanets"},
	{ "GM"  , 117     , "s", "Taiko"},
	{ "g(1)", 117     , "s", "Concert BassDrum"},
	{ "GM"  , 118     , "s", "Melodic Tom 1"},
	{ "g(1)", 118     , "s", "Melodic Tom 2"},
	{ "GM"  , 119     , "s", "Synth Drum"},
	{ "g(1)", 119     , "s", "Analog Tom"},
	{ "g(2)", 119     , "s", "Electric Drum"},
	{ "GM"  , 120     , "s", "Reverse Cymbal"},
	{ "GM"  , 121     , "s", "Gtr.Fret Noise"},
	{ "g(1)", 121     , "s", "Gtr.CuttingNoise"},
	{ "g(2)", 121     , "s", "Bass String Slap"},
	{ "GM"  , 122     , "s", "Breath Noise"},
	{ "g(1)", 122     , "s", "Flute Key Click"},
	{ "GM"  , 123     , "d", "Seashore"},
	{ "g(1)", 123     , "d", "Rain"},
	{ "g(2)", 123     , "s", "Thunder"},
	{ "g(3)", 123     , "d", "Wind"},
	{ "g(4)", 123     , "s", "Stream"},
	{ "g(5)", 123     , "d", "Bubble"},
	{ "GM"  , 124     , "d", "Bird Tweet 1"},
	{ "g(1)", 124     , "s", "Dog"},
	{ "g(2)", 124     , "s", "Horse Gallop"},
	{ "g(3)", 124     , "s", "Bird Tweet 2"},
	{ "GM"  , 125     , "s", "Telephone Ring 1"},
	{ "g(1)", 125     , "s", "Telephone Ring 2"},
	{ "g(2)", 125     , "s", "Door Creaking"},
	{ "g(3)", 125     , "s", "Door Slamming"},
	{ "g(4)", 125     , "s", "Scratch"},
	{ "g(5)", 125     , "s", "Wind Chime"},
	{ "GM"  , 126     , "d", "Helicopter"},
	{ "g(1)", 126     , "d", "Car Engine"},
	{ "g(2)", 126     , "s", "Car Stop"},
	{ "g(3)", 126     , "s", "Car Pass"},
	{ "g(4)", 126     , "s", "Car Crash"},
	{ "g(5)", 126     , "d", "Siren"},
	{ "g(6)", 126     , "s", "Train"},
	{ "g(7)", 126     , "d", "Jetplane"},
	{ "g(8)", 126     , "d", "Starship"},
	{ "g(9)", 126     , "d", "Burst Noise"},
	{ "GM"  , 127     , "d", "Applause"},
	{ "g(1)", 127     , "s", "Laughing"},
	{ "g(2)", 127     , "s", "Screaming"},
	{ "g(3)", 127     , "s", "Punch"},
	{ "g(4)", 127     , "s", "Heart Beat"},
	{ "g(5)", 127     , "s", "Footsteps"},
	{ "GM"  , 128     , "s", "Gun Shot"},
	{ "g(1)", 128     , "s", "Machine Gun"},
	{ "g(2)", 128     , "d", "Lasergun"},
	{ "g(3)", 128     , "s", "Explosion"},
	{ "g(d)", 1       , "d", "STANDARD Kit"},
	{ "g(d)", 9       , "d", "ROOM Kit"},
	{ "g(d)", 17      , "d", "POWER Kit"},
	{ "g(d)", 25      , "d", "ELECTRONIC Kit"},
	{ "g(d)", 26      , "d", "ANALOG Kit"},
	{ "g(d)", 33      , "d", "JAZZ Kit"},
	{ "g(d)", 41      , "d", "BRUSH Kit"},
	{ "g(d)", 49      , "d", "ORCHESTRA Kit"},
	{ "g(d)", 57      , "d", "SFX Kit"}
};