#include "pcg_converter.h"
#include <iostream>
#include <format>

std::vector<TritonStruct> PCG_Converter::arpeggiator_global_conversions = {
	{ ""					, "octave_motion"	, 16, 0, 1, EVarType::Unsigned },
	{ ""					, "arpeggio_type"	, 16, 2, 3, EVarType::Unsigned },
	{ ""					, "tone_mode"		, 16, 4, 4, EVarType::Unsigned },
	{ ""					, "fixed_note_mode"	, 16, 5, 5, EVarType::Unsigned },
	{ ""					, "length"			, 17, 0, 7, EVarType::Unsigned },
	{ ""					, "tone_note_no.1"	, 20, 0, 7 },
	{ ""					, "tone_note_no.2"	, 21, 0, 7 },
	{ ""					, "tone_note_no.3"	, 22, 0, 7 },
	{ ""					, "tone_note_no.4"	, 23, 0, 7 },
	{ ""					, "tone_note_no.5"	, 24, 0, 7 },
	{ ""					, "tone_note_no.6"	, 25, 0, 7 },
	{ ""					, "tone_note_no.7"	, 26, 0, 7 },
	{ ""					, "tone_note_no.8"	, 27, 0, 7 },
	{ ""					, "tone_note_no.9"	, 28, 0, 7 },
	{ ""					, "tone_note_no.10"	, 29, 0, 7 },
	{ ""					, "tone_note_no.11"	, 30, 0, 7 },
	{ ""					, "tone_note_no.12"	, 31, 0, 7 },
};

std::vector<TritonStruct> PCG_Converter::arpeggiator_step_conversions = {
	{ ""					, "pitch_offset", 32, 0, 7, EVarType::Signed },
	{ ""					, "gate"		, 33, 0, 7, EVarType::Unsigned },
	{ ""					, "velocity"	, 34, 0, 7, EVarType::Unsigned },
	{ ""					, "flam"		, 35, 0, 7, EVarType::Signed },
	{ ""					, "tone_0"		, 37, 0, 0 },
	{ ""					, "tone_1"		, 37, 1, 1 },
	{ ""					, "tone_2"		, 37, 2, 2 },
	{ ""					, "tone_3"		, 37, 3, 3 },
	{ ""					, "tone_4"		, 37, 4, 4 },
	{ ""					, "tone_5"		, 37, 5, 5 },
	{ ""					, "tone_6"		, 37, 6, 6 },
	{ ""					, "tone_7"		, 37, 7, 7 },
	{ ""					, "tone_8"		, 36, 0, 0 },
	{ ""					, "tone_9"		, 36, 1, 1 },
	{ ""					, "tone_10"		, 36, 2, 2 },
	{ ""					, "tone_11"		, 36, 3, 3 },
};

std::vector<std::string> PCG_Converter::drumkit_notes = {
	"c-1", "c#-1", "d-1", "d#-1", "e-1", "f-1", "f#-1", "g-1", "g#-1", "a-1", "a#-1", "b-1",
	"c0", "c#0", "d0", "d#0", "e0", "f0", "f#0", "g0", "g#0", "a0", "a#0", "b0",
	"c1", "c#1", "d1", "d#1", "e1", "f1", "f#1", "g1", "g#1", "a1", "a#1", "b1",
	"c2", "c#2", "d2", "d#2", "e2", "f2", "f#2", "g2", "g#2", "a2", "a#2", "b2",
	"c3", "c#3", "d3", "d#3", "e3", "f3", "f#3", "g3", "g#3", "a3", "a#3", "b3",
	"c4", "c#4", "d4", "d#4", "e4", "f4", "f#4", "g4", "g#4", "a4", "a#4", "b4",
	"c5", "c#5", "d5", "d#5", "e5", "f5", "f#5", "g5", "g#5", "a5", "a#5", "b5",
	"c6", "c#6", "d6", "d#6", "e6", "f6", "f#6", "g6", "g#6", "a6", "a#6", "b6",
	"c7", "c#7", "d7", "d#7", "e7", "f7", "f#7", "g7", "g#7", "a7", "a#7", "b7",
	"c8", "c#8", "d8", "d#8", "e8", "f8", "f#8", "g8", "g#8", "a8", "a#8", "b8",
	"c9", "c#9", "d9", "d#9", "e9", "f9", "f#9", "g9",
};


std::vector<TritonStruct> PCG_Converter::drumkit_conversions = {
	{ "" , "higher_bank"			, 16, 0, 7, EVarType::Unsigned },
	{ "" , "higher_start_offset"	, 17, 0, 0, EVarType::Unsigned },
	{ "" , "higher_reverse"			, 17, 1, 1, EVarType::Unsigned },
	{ "" , "higher_sample_no"		, 18, 0, 7, EVarType::Unsigned, 19, 0, 7 },
	{ "" , "higher_level"			, 20, 0, 7, EVarType::Signed },
	{ "" , "higher_transpose"		, 21, 0, 7, EVarType::Signed },
	{ "" , "higher_tune"			, 22, 0, 7, EVarType::Signed },
	{ "" , "higher_attack_level"	, 23, 0, 7, EVarType::Signed },
	{ "" , "higher_decay_level"		, 24, 0, 7, EVarType::Signed },
	{ "" , "higher_cutoff_level"	, 25, 0, 7, EVarType::Signed },
	{ "" , "higher_resonance_level"	, 26, 0, 7, EVarType::Signed },
	{ "" , "lower_bank"				, 28, 0, 7, EVarType::Unsigned },
	{ "" , "lower_start_offset"		, 29, 0, 0, EVarType::Unsigned },
	{ "" , "lower_reverse"			, 29, 1, 1, EVarType::Unsigned },
	{ "" , "lower_sample_no"		, 30, 0, 7, EVarType::Unsigned, 31, 0, 7 },
	{ "" , "lower_level"			, 32, 0, 7, EVarType::Signed },
	{ "" , "lower_transpose"		, 33, 0, 7, EVarType::Signed },
	{ "" , "lower_tune"				, 34, 0, 7, EVarType::Signed },
	{ "" , "lower_attack_level"		, 35, 0, 7, EVarType::Signed },
	{ "" , "lower_decay_level"		, 36, 0, 7, EVarType::Signed },
	{ "" , "lower_cutoff_level"		, 37, 0, 7, EVarType::Signed },
	{ "" , "lower_resonance_level"	, 38, 0, 7, EVarType::Signed },
	{ "" , "pan"					, 40, 0, 7, EVarType::Signed },
	{ "" , "bus_select"				, 41, 0, 7, EVarType::Unsigned },
	{ "" , "send_1_level"			, 42, 0, 7, EVarType::Unsigned },
	{ "" , "send_2_level"			, 43, 0, 7, EVarType::Unsigned },
	{ "" , "exclusive_group"		, 44, 0, 7, EVarType::Unsigned },
	{ "" , "voice_assign"			, 45, 0, 0, EVarType::Unsigned },
	{ "" , "single_trigger"			, 45, 1, 1, EVarType::Unsigned },
	{ "" , "receive_note_on"		, 45, 2, 2, EVarType::Unsigned },
	{ "" , "receive_note_off"		, 45, 3, 3, EVarType::Unsigned },
	{ "" , "velocity_sample_switch"	, 46, 0, 7, EVarType::Unsigned },
};
